{"name": "Тест: ошибка 404 not found при передаче несуществующих полей login и password", "status": "passed", "attachments": [{"name": "log", "source": "79a2cb3e-6550-471f-a416-74431ae8052e-attachment.txt", "type": "text/plain"}], "start": 1717679538180, "stop": 1717679538522, "uuid": "241bd77e-0722-4d69-ab40-543e943dc883", "historyId": "093dcde71d8a6996fe42075fad972d9d", "testCaseId": "093dcde71d8a6996fe42075fad972d9d", "fullName": "tests.test_login_courier.TestPostLoginCourier#test_login_courier_with_non_existent_login_and_password_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestPostLoginCourier"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "1796-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}