{"name": "Тест: ошибка 404 not found при передаче несуществующих полей login и password", "status": "passed", "attachments": [{"name": "log", "source": "fa9055a2-1964-44fc-a800-ac8a614349a5-attachment.txt", "type": "text/plain"}], "start": 1717768240433, "stop": 1717768240682, "uuid": "e33a8d72-c326-4d15-b24b-c218f4cdd42f", "historyId": "093dcde71d8a6996fe42075fad972d9d", "testCaseId": "093dcde71d8a6996fe42075fad972d9d", "fullName": "tests.test_login_courier.TestPostLoginCourier#test_login_courier_with_non_existent_login_and_password_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestPostLoginCourier"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "8512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}