{"name": "Тест: ошибка 404 not found при передаче несуществующих полей login и password", "status": "passed", "start": 1717930447051, "stop": 1717930447316, "uuid": "a9ba47f8-a95f-4347-b586-aa4d8085a141", "historyId": "093dcde71d8a6996fe42075fad972d9d", "testCaseId": "093dcde71d8a6996fe42075fad972d9d", "fullName": "tests.test_login_courier.TestPostLoginCourier#test_login_courier_with_non_existent_login_and_password_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestPostLoginCourier"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "16456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}