{"name": "Тест: нельзя дважды удалить курьера", "status": "passed", "start": 1717930436274, "stop": 1717930437348, "uuid": "a3f40e2d-3ab4-493f-9dc4-e8948bcf9281", "historyId": "2d57f33d751b0dabfd0e192936ea3d80", "testCaseId": "2d57f33d751b0dabfd0e192936ea3d80", "fullName": "tests.test_delete_courier.TestDeleteCourier#test_delete_courier_twice_shows_code_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "16456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_delete_courier"}]}